# Generated by Django 2.0.3 on 2018-03-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_auto_20180314_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='area',
            field=models.CharField(max_length=15),
        ),
    ]
